export const socialHistory = [
  {
    data: {
      neverAlcohol: true,
      rarelyAlcohol: false,
      sometimesAlcohol: false,
      usuallyAlcohol: false,
      neverGym: false,
      rarelyGym: false,
      sometimesGym: false,
      usuallyGym: true,
      neverDrugs: true,
      rarelyDrugs: false,
      usuallyDrugs: false,
      descriptionDrug: 'Ninguna',
      neverCoffee: false,
      rarelyCoffee: false,
      sometimesCoffee: true,
      usuallyCoffee: false,
      neverSmoke: true,
      rarelySmoke: false,
      usuallySmoke: false,
      descriptionSmoke: 'Ninguno',
      patient: {
        connect: { documentNumber: 38084125 },
      },
    },
  },
  {
    data: {
      neverAlcohol: false,
      rarelyAlcohol: false,
      sometimesAlcohol: false,
      usuallyAlcohol: true,
      neverGym: true,
      rarelyGym: false,
      sometimesGym: false,
      usuallyGym: false,
      neverDrugs: true,
      rarelyDrugs: false,
      usuallyDrugs: false,
      descriptionDrug: 'Ninguna',
      neverCoffee: false,
      rarelyCoffee: true,
      sometimesCoffee: false,
      usuallyCoffee: false,
      neverSmoke: true,
      rarelySmoke: false,
      usuallySmoke: false,
      descriptionSmoke: 'Ninguno',
      patient: {
        connect: { documentNumber: 38084123 },
      },
    },
  },
];
