export const nephrologistType = [
  {
    create: {
      elevatedBloodPressure: true,
      diabetes: true,
      idiopathic: 'No',
      autoimmune: true,
      nephropathy: true,
      creatinine: 9,
      clearence: 8,
      access: 'No',
      peritoneal: 'No',
      waitingYears: 3,
      operatives: 5,
    },
    update: {},
    where: { id: 1 },
  },
  {
    create: {
      elevatedBloodPressure: false,
      diabetes: false,
      idiopathic: 'No',
      autoimmune: true,
      nephropathy: true,
      creatinine: 6,
      clearence: 3,
      access: 'Si',
      peritoneal: 'Si',
      waitingYears: 1,
      operatives: 2,
    },
    update: {},
    where: { id: 2 },
  },
  {
    create: {
      elevatedBloodPressure: true,
      diabetes: false,
      idiopathic: 'Si',
      autoimmune: false,
      nephropathy: true,
      creatinine: 4,
      clearence: 3,
      access: 'No',
      peritoneal: 'Si',
      waitingYears: 5,
      operatives: 1,
    },
    update: {},
    where: { id: 3 },
  },
];
